name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:        
      - name: Display learning message
        run: echo 'Learning GitHub Actions'
        
      - name: Display GitHub actor and ref
        run: echo "github.actor: ${{ github.actor }}, github.ref: ${{ github.ref }}"
