name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Learning github actions'
      - run: echo 'github.actor: ${{ github.actor }}, github.ref: ${{ github.ref }}'
